spring:
  application:
    name: "TicketBookingSystem"
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: "/api/v1"

logging:
  level:
    org:
      springframework:
        security: "DEBUG"